apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "webapp.name" . }}-presync
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "0"
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "[PreSync] running schema migration for {{ .Values.labels.env }}"
              sleep 2
              echo "[PreSync] migration done"
