apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ordered-app
  namespace: argocd
spec:
  project: platform-dev
  source:
    repoURL: https://github.com/desotech-it/DSK213-PUBLIC.git
    targetRevision: main
    path: lab04-sync-waves-hooks/apps/ordered-app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
