apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-iu
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: web=nginx
    argocd-image-updater.argoproj.io/web.update-strategy: alphabetical
    argocd-image-updater.argoproj.io/web.allow-tags: regexp:^1\.(2[5-9]|3[0-9])-alpine$
    argocd-image-updater.argoproj.io/web.kustomize.image-name: nginx
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: platform-dev
  source:
    repoURL: https://github.com/desotech-it/DSK213-PUBLIC.git
    targetRevision: main
    path: lab08-argo-image-updater/apps/demo-iu
    kustomize:
      images:
        - nginx:1.25-alpine
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-iu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
