apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-fleet
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev-fleet
          - env: stage
            namespace: stage-fleet
          - env: prod
            namespace: prod-fleet
  template:
    metadata:
      name: '{{ .env }}-demo-fleet'
      namespace: argocd
    spec:
      project: platform-fleet
      source:
        repoURL: https://github.com/desotech-it/DSK213-PUBLIC.git
        targetRevision: main
        path: lab02-apps-and-projects/apps/demo
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
