apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-fleet
  namespace: argocd
spec:
  description: Multi-environment fleet project for demo-fleet ApplicationSet
  sourceRepos:
    - https://github.com/desotech-it/DSK213-PUBLIC.git
  destinations:
    - namespace: dev-*
      server: https://kubernetes.default.svc
    - namespace: stage-*
      server: https://kubernetes.default.svc
    - namespace: prod-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
  orphanedResources:
    warn: true
