apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kustomize
  labels:
    app: demo-kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kustomize
  template:
    metadata:
      labels:
        app: demo-kustomize
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
