apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-stage
  namespace: argocd
spec:
  description: Staging workloads only
  sourceRepos:
    - https://github.com/desotech-it/DSK213-PUBLIC.git
  destinations:
    - namespace: stage-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
