apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-meta
  namespace: argocd
spec:
  description: Meta project for app-of-apps and ApplicationSet patterns
  sourceRepos:
    - https://github.com/desotech-it/DSK213-PUBLIC.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: dev-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: ApplicationSet
  orphanedResources:
    warn: true
