apiVersion: v1
kind: Secret
metadata:
  name: cluster-eu-west
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: production
    region: eu-west
type: Opaque
stringData:
  name: eu-west-sim
  server: https://eu-west.example.com
  config: '{"tlsClientConfig":{"insecure":true}}'
